/** Stable UI-debug API. Keep an ID with its conceptual panel across refactors. */
export const debugRegions = [
  { id: 'HDR', description: 'Application header', source: 'app/Shell.tsx' },
  { id: 'BLS', description: 'Server connection loading screen', source: 'app/Shell.tsx' },
  { id: 'WRK', description: 'Whole Work home content region', source: 'features/work/Home.tsx' },
  { id: 'WHT', description: 'Work home title and description group', source: 'features/work/Home.tsx' },
  { id: 'ACT', description: 'Active workspaces', source: 'features/work/Home.tsx' },
  { id: 'WLS', description: 'Active workspace list', source: 'features/work/Home.tsx' },
  { id: 'WRC', description: 'Workspace row', source: 'features/work/Home.tsx' },
  { id: 'LIB', description: 'Library', source: 'features/work/Home.tsx' },
  { id: 'BKC', description: 'Library book card', source: 'features/work/Home.tsx' },
  { id: 'LSD', description: 'Library source details drawer', source: 'features/work/LibrarySource.tsx' },
  { id: 'LSI', description: 'Library source inspection section', source: 'features/work/LibrarySource.tsx' },
  { id: 'WCM', description: 'Workspace creation and setup modal', source: 'features/work/LibrarySource.tsx' },
  { id: 'WMP', description: 'Workspace setup pass-model group', source: 'features/work/LibrarySource.tsx' },
  { id: 'ARD', description: 'Archive drawer', source: 'features/work/Home.tsx' },
  { id: 'ARI', description: 'Archived workspace row', source: 'features/work/Home.tsx' },
  { id: 'WSP', description: 'Workspace overview', source: 'features/pipeline/Workspace.tsx' },
  { id: 'WHH', description: 'Workspace header', source: 'features/pipeline/Workspace.tsx' },
  { id: 'PHR', description: 'Workspace phase rail', source: 'features/pipeline/Workspace.tsx' },
  { id: 'PRC', description: 'Unprepared workspace card', source: 'features/pipeline/Workspace.tsx' },
  { id: 'STF', description: 'Sections toolbar and filters', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SCT', description: 'Sections table card', source: 'features/pipeline/Workspace.tsx' },
  { id: 'PMA', description: 'Pipeline models accordion', source: 'features/pipeline/Workspace.tsx' },
  { id: 'MPA', description: 'Pipeline model · Pass 1', source: 'features/pipeline/Workspace.tsx' },
  { id: 'MPB', description: 'Pipeline model · Pass 2', source: 'features/pipeline/Workspace.tsx' },
  { id: 'MPC', description: 'Pipeline model · Pass 3', source: 'features/pipeline/Workspace.tsx' },
  { id: 'MPD', description: 'Pipeline model · Pass 4', source: 'features/pipeline/Workspace.tsx' },
  { id: 'MPE', description: 'Pipeline model · Pass 5', source: 'features/pipeline/Workspace.tsx' },
  { id: 'LVA', description: 'Live activity accordion', source: 'features/pipeline/Workspace.tsx' },
  { id: 'RAL', description: 'Recent execution card', source: 'features/pipeline/Workspace.tsx' },
  { id: 'PUL', description: 'Publication log card', source: 'features/pipeline/Workspace.tsx' },
  { id: 'PVD', description: 'Section preview drawer', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SMG', description: 'Section model override group', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SMA', description: 'Section model override · Pass 1', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SMB', description: 'Section model override · Pass 2', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SMC', description: 'Section model override · Pass 3', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SMD', description: 'Section model override · Pass 4', source: 'features/pipeline/Workspace.tsx' },
  { id: 'SME', description: 'Section model override · Pass 5', source: 'features/pipeline/Workspace.tsx' },
  { id: 'ACM', description: 'Archive confirmation modal', source: 'features/pipeline/Workspace.tsx' },
  { id: 'REV', description: 'Review page', source: 'features/review/Review.tsx' },
  { id: 'RVH', description: 'Review heading and approval', source: 'features/review/Review.tsx' },
  { id: 'RVF', description: 'Review search and filters', source: 'features/review/Review.tsx' },
  { id: 'RVC', description: 'Review category filters', source: 'features/review/Review.tsx' },
  { id: 'RVB', description: 'Review visible-scope bulk action', source: 'features/review/Review.tsx' },
  { id: 'RVL', description: 'Review list and detail layout', source: 'features/review/Review.tsx' },
  { id: 'RFL', description: 'Review terminology list', source: 'features/review/Review.tsx' },
  { id: 'RVD', description: 'Review term detail', source: 'features/review/Review.tsx' },
  { id: 'RVE', description: 'Review evidence group', source: 'features/review/Review.tsx' },
  { id: 'RVM', description: 'Review navigation footer', source: 'features/review/Review.tsx' },
  { id: 'RUC', description: 'Unsaved Review form modal', source: 'features/review/Review.tsx' },
  { id: 'RBM', description: 'Bulk Review confirmation modal', source: 'features/review/Review.tsx' },
  { id: 'RDR', description: 'Reader page', source: 'features/reader/Reader.tsx' },
  { id: 'RSH', description: 'Reader shell', source: 'features/reader/Reader.tsx' },
  { id: 'RBL', description: 'Reader book list', source: 'features/reader/Reader.tsx' },
  { id: 'RBB', description: 'Reader book card', source: 'features/reader/Reader.tsx' },
  { id: 'RBC', description: 'Reader content region', source: 'features/reader/Reader.tsx' },
  { id: 'RCO', description: 'Reader chapter controls', source: 'features/reader/Reader.tsx' },
  { id: 'RPG', description: 'Reader translated chapter', source: 'features/reader/Reader.tsx' },
  { id: 'RSL', description: 'Reader text selection actions', source: 'features/reader/Reader.tsx' },
  { id: 'RMK', description: 'Reader markers accordion', source: 'features/reader/Reader.tsx' },
  { id: 'RCM', description: 'Reader context modal', source: 'features/reader/Reader.tsx' },
  { id: 'PHD', description: 'Phase detail page', source: 'features/pipeline/Phase.tsx' },
  { id: 'PLD', description: 'Phase loading card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PHH', description: 'Phase detail heading', source: 'features/pipeline/Phase.tsx' },
  { id: 'PHM', description: 'Phase metrics group', source: 'features/pipeline/Phase.tsx' },
  { id: 'PMT', description: 'Phase metric card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PSR', description: 'Prepare source structure card', source: 'features/pipeline/PrepareContent.tsx' },
  { id: 'PPR', description: 'Prepare source preview card', source: 'features/pipeline/PrepareContent.tsx' },
  { id: 'PSM', description: 'Prepare source metadata card', source: 'features/pipeline/PrepareContent.tsx' },
  { id: 'PCK', description: 'Prepare checks card', source: 'features/pipeline/PrepareContent.tsx' },
  { id: 'RPM', description: 'Prepare rebuild confirmation modal', source: 'features/pipeline/Phase.tsx' },
  { id: 'PAN', description: 'Analyse units card', source: 'features/pipeline/AnalyseContent.tsx' },
  { id: 'PAV', description: 'Analyse P1 source and result preview', source: 'features/pipeline/AnalyseContent.tsx' },
  { id: 'AUM', description: 'Analyse unit run confirmation', source: 'features/pipeline/AnalyseContent.tsx' },
  { id: 'PAE', description: 'Analyse empty-state card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PAC', description: 'Analyse P1 data action card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PRM', description: 'P1 reset confirmation modal', source: 'features/pipeline/Phase.tsx' },
  { id: 'PGD', description: 'Analyse generated data card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PAR', description: 'Analyse artifacts card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PTS', description: 'Translate pass summary card', source: 'features/pipeline/TranslateContent.tsx' },
  { id: 'PSC', description: 'Translate chunk progress card', source: 'features/pipeline/TranslateContent.tsx' },
  { id: 'TPV', description: 'Translate pass source and result preview', source: 'features/pipeline/TranslateContent.tsx' },
  { id: 'TCM', description: 'Translate targeted pass confirmation', source: 'features/pipeline/TranslateContent.tsx' },
  { id: 'PDG', description: 'Translate diagnostics card', source: 'features/pipeline/TranslateContent.tsx' },
  { id: 'PPO', description: 'Publish output card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PPV', description: 'Publish validation card', source: 'features/pipeline/Phase.tsx' },
  { id: 'PMD', description: 'Publish metadata card', source: 'features/pipeline/Phase.tsx' },
  { id: 'SET', description: 'Settings modal', source: 'app/Shell.tsx' },
  { id: 'STB', description: 'Settings tabs', source: 'app/Shell.tsx' },
  { id: 'SPA', description: 'Settings · Paths', source: 'app/Shell.tsx' },
  { id: 'SPM', description: 'Settings · Models', source: 'app/Shell.tsx' },
  { id: 'MPR', description: 'Settings model profile row', source: 'app/Shell.tsx' },
  { id: 'SPI', description: 'Settings · Interface', source: 'app/Shell.tsx' },
  { id: 'SPD', description: 'Settings · Debug', source: 'app/Shell.tsx' },
] as const

export type DebugId = (typeof debugRegions)[number]['id']
export const pipelineModelIds = ['MPA', 'MPB', 'MPC', 'MPD', 'MPE'] as const satisfies readonly DebugId[]
export const sectionModelIds = ['SMA', 'SMB', 'SMC', 'SMD', 'SME'] as const satisfies readonly DebugId[]

export function debugTag(id: DebugId, entityId?: string) {
  return { 'data-ui-debug-id': id, ...(entityId === undefined ? {} : { 'data-entity-id': entityId }) }
}
