import { useParams } from '@tanstack/react-router'
import { endpoint, useApi } from '../../api/client'
import { pipelineSchema, preparationSchema, profilesSchema, usageSchema, workspacesSchema, type Usage } from '../../api/schema'
import { Back, Empty, ErrorNote, Panel, ProfileSwatch } from '../../components/ui/common'
import { Activity, PassMark, phaseStatus } from './Workspace'
import { Action } from './Action'
const fields = ['input_tokens','cached_input_tokens','reasoning_output_tokens','output_tokens'] as const
const labels = ['Input','Cache','Reason','Output']
export function usageTotals(usage: Usage | undefined, numbers: number[]) {
  return fields.map(field => {
    const aggregates = usage?.units.flatMap(u => u.passes.filter(p => numbers.includes(p.pass_no)).map(p => p[field])) ?? []
    const measured = aggregates.filter(a => a.value !== null)
    return { value: measured.length ? measured.reduce((sum,a) => sum + a.value!, 0) : null, partial: aggregates.some(a => a.unknown_attempts > 0 || a.value === null) }
  })
}
const measured = (value: ReturnType<typeof usageTotals>[number]) => value.value == null ? '—' : `${value.value.toLocaleString()}${value.partial ? ' (partial)' : ''}`
export function PhasePage() {
  const { workspaceId: id = '', phase = 'prepare' } = useParams({ strict: false })
  const all = useApi('/api/workspaces', workspacesSchema)
  const workspace = all.data?.workspaces.find(w => w.workspace_id === id)
  const query = useApi(endpoint(id,'pipeline'), pipelineSchema, !!workspace?.prepared)
  const usage = useApi(endpoint(id,'usage'), usageSchema, !!workspace?.prepared && ['analyse','translate'].includes(phase))
  const profiles = useApi(endpoint(id,'profiles'), profilesSchema, !!workspace?.prepared)
  const preparation = useApi(endpoint(id,'preparation'), preparationSchema, !!workspace?.prepared && phase === 'prepare')
  const p = query.data
  const title = ({ prepare: 'Prepare', analyse: 'Analyse', translate: 'Translate', publish: 'Publish' } as Record<string,string>)[phase] ?? phase
  const state = p ? phaseStatus(p,phase) : 'blocked'
  const totals = usageTotals(usage.data, phase === 'analyse' ? [1] : [2,3,4,5])
  const metrics = phase === 'prepare' ? [['Format',p?.metadata.format ?? '—'],['Sections',p?.sections.length ?? '—'],['Processable',p?.sections.filter(s => s.processing !== 'excluded').length ?? '—'],['Words',p?.metadata.word_count?.toLocaleString() ?? '—']] : phase === 'publish' ? [['Status',p?.publication.state ?? '—'],['Format',p?.publication.current ? 'EPUB' : '—'],['Sections',p?.sections.filter(s => s.processing !== 'excluded').length ?? '—'],['Size',p?.publication.size_bytes == null ? '—' : `${p.publication.size_bytes.toLocaleString()} bytes`]] : totals.map((t,i) => [labels[i],measured(t)])
  const currentProfile = (n:number) => { const profile=profiles.data?.resolved_passes[String(n)];return <span className="phase-model"><ProfileSwatch index={profile?.stable_palette_index} name={profile?.name ?? 'Unavailable'} />{profile?.name ?? '—'}</span> }
  return <main className="main phase-detail-page"><Back id={id} /><div className="phase-detail-head"><div className="phase-detail-title"><div className="eyebrow">{title} · {p?.metadata.title ?? workspace?.metadata.title ?? 'Workspace'}</div><h1>{title}</h1><div className="phase-detail-meta">Phase details and execution diagnostics</div></div><span className={`phase-status-badge ${state}`}>{state === 'done' ? 'Complete' : state === 'blocked' ? 'Blocked' : state === 'error' ? 'Failed' : p?.active_job ? 'Running' : 'Ready'}</span></div><ErrorNote error={query.error ?? usage.error ?? profiles.error} retry={() => void query.refetch()} />
    <div className="phase-metrics">{metrics.map(([label,value]) => <div className="phase-metric" key={label}><div className="phase-metric-label">{label}</div><div className="phase-metric-value" title={String(value)}>{value}</div></div>)}</div>
    {!p ? <Empty>{workspace?.prepared ? 'Loading phase details…' : <>Source structure has not been inspected yet. Run Prepare from the workspace to create the frozen section and chunk plan.{workspace && <Action workspace={workspace} />}</>}</Empty> : state === 'blocked' && phase !== 'prepare' ? <Empty>Complete the preceding phase before {title.toLowerCase()}.</Empty> : <div className="phase-detail-grid"><div className="phase-detail-stack">
      {phase === 'prepare' && <Panel title="Source structure"><table className="phase-detail-table prepare-structure"><thead><tr><th>Section</th><th>Content type</th><th>Processing</th><th>P1</th></tr></thead><tbody>{p.sections.map(s => <tr key={s.id}><td title={s.title ?? s.fallback_excerpt}>{String(s.ordinal).padStart(2,'0')} · {s.title || s.fallback_excerpt}</td><td>{s.content_type.replaceAll('_',' ')}</td><td>{s.processing}</td><td>{s.processing === 'full' ? 'Included' : '—'}</td></tr>)}</tbody></table></Panel>}
      {phase === 'analyse' && <Panel title="Analysis units"><div className="diagnostic-scroll"><table className="phase-detail-table usage-table"><thead><tr><th>Section / unit</th><th>Model</th><th>Status</th>{labels.map(label => <th className="num" key={label}>{label}</th>)}</tr></thead><tbody>{p.analysis.units.map(unit => { const actual = usage.data?.units.find(u => u.unit_id === unit.id)?.passes.find(v => v.pass_no === 1); return <tr key={unit.id}><td title={unit.id}>{unit.id}</td><td title={actual?.reported_model ?? actual?.requested_model ?? 'Unavailable'}>{actual?.reported_model ?? actual?.requested_model ?? '—'}</td><td>{unit.state}</td>{fields.map(f => <td className="num" key={f}>{actual?.[f].value?.toLocaleString() ?? '—'}</td>)}</tr> })}</tbody></table></div>{!p.analysis.units.length && <Empty>No persisted analysis plan yet.</Empty>}</Panel>}
      {phase === 'translate' && <><Panel title="Pass summary"><div className="diagnostic-scroll"><table className="phase-detail-table pass-summary"><thead><tr><th>Pass</th><th>Default profile</th><th>Units</th>{labels.map(label => <th className="num" key={label}>{label}</th>)}</tr></thead><tbody>{[2,3,4,5].map(n => <tr key={n}><td>P{n}</td><td title="Current default; actual historical models may differ by section.">{currentProfile(n)}</td><td title={n < 5 ? 'Retained checkpoints have not been revalidated against current inputs.' : 'Verified completed final units'}>{p.units.filter(u => u.passes[String(n)]?.checkpoint_state === 'completed').length}/{p.units.length}{n < 5 ? ' verified' : ''}</td>{usageTotals(usage.data,[n]).map((t,i) => <td className="num" key={i} title={measured(t)}>{measured(t)}</td>)}</tr>)}</tbody></table></div></Panel><Panel title="Section progress"><table className="phase-detail-table"><thead><tr><th>Section</th>{[2,3,4,5].map(n => <th key={n}>P{n}</th>)}</tr></thead><tbody>{p.sections.filter(s => s.processing !== 'excluded').map(s => <tr key={s.id}><td title={s.title ?? s.fallback_excerpt}>{s.title || s.fallback_excerpt}</td>{[2,3,4,5].map(n => <td key={n}><PassMark section={s} number={n} /></td>)}</tr>)}</tbody></table></Panel></>}
      {phase === 'publish' && <><Panel title="Published output"><dl className="phase-kv"><dt>File</dt><dd>{p.publication.filename ?? '—'}</dd><dt>Resource</dt><dd>{p.publication.current ? 'Current workspace EPUB' : 'Unavailable'}</dd><dt>Language</dt><dd>{p.publication.target_language}</dd><dt>Edition</dt><dd>{p.publication.generated_by ?? '—'}</dd><dt>Source sections</dt><dd>{p.sections.length}</dd><dt>Excluded</dt><dd>{p.sections.filter(s => s.processing === 'excluded').length}</dd></dl>{p.publication.current && <a className="secondary-btn download" href={endpoint(id,'publication/download')}>Open EPUB</a>}{p.publication.last_error && <p className="subtitle">{p.publication.last_error}</p>}</Panel><Panel title="Package validation">{p.publication.checks.length ? p.publication.checks.map(check => <p className="phase-check" key={check}><span className="phase-check-icon">✓</span>{check}</p>) : <Empty>No current publication validation results.</Empty>}</Panel></>}
    </div><div className="phase-detail-stack">
      {phase === 'translate' ? <Activity id={id} expanded title="Recent execution" /> : phase === 'analyse' ? <Panel title="Generated data"><dl className="phase-kv"><dt>Terms / entities</dt><dd>{p.review.summary?.total ?? '—'}</dd><dt>Analysis units</dt><dd>{p.analysis.units.length}</dd><dt>Default profile</dt><dd>{currentProfile(1)}</dd><dt>Review gate</dt><dd>{p.approved ? 'Committed approval' : p.analysis.complete ? 'Ready for review' : 'Not ready'}</dd></dl></Panel> : <Panel title={phase === 'prepare' ? 'Source metadata' : 'Metadata'}><dl className="phase-kv"><dt>Title</dt><dd>{p.metadata.title}</dd><dt>Author</dt><dd>{p.metadata.creators.join(', ') || '—'}</dd><dt>Source language</dt><dd>{p.metadata.language ?? '—'}</dd>{phase === 'prepare' ? <><dt>Source</dt><dd>{p.preparation.source_id}</dd></> : <><dt>Output language</dt><dd>{p.publication.target_language}</dd><dt>Publisher</dt><dd>{p.publication.generated_by ?? '—'}</dd></>}</dl></Panel>}
      {phase === 'prepare' && <Panel title="Checks">{(preparation.data?.checks ?? []).map(check => <p className="phase-check" key={check}><span className="phase-check-icon">✓</span>{check}</p>)}<ErrorNote error={preparation.error} /><p className="subtitle">{preparation.data?.unavailable}</p><p className="subtitle">Reading order: {preparation.data?.reading_order?.replaceAll('_',' ') ?? '—'}</p></Panel>}
      {phase === 'analyse' && <Panel title="Artifacts"><p className="phase-check">{p.artifacts.terminology ? '✓' : '○'} Terminology candidates · {p.artifacts.terminology ? 'Available' : 'Not available'}</p><p className="phase-check">{p.artifacts.book_memory ? '✓' : '○'} Book memory · {p.artifacts.book_memory ? 'Available' : 'Not available'}</p></Panel>}
      {phase === 'translate' && <Panel title="Diagnostics"><p className="subtitle">Usage covers recorded attempts, including retries. Cache and reasoning can be subsets; do not add these totals together.</p><ErrorNote error={usage.error} />{usage.data?.warning && <p className="subtitle">{usage.data.warning}</p>}<div className="execution-diagnostics">{usage.data?.units.flatMap(u => u.passes.filter(pass => pass.pass_no > 1).map(pass => <details key={`${u.unit_id}-${pass.pass_no}`}><summary>{u.unit_id} · P{pass.pass_no} · {pass.physical_attempt_count} attempts</summary><p>{pass.provider ?? '—'} · {pass.reported_model ?? pass.requested_model ?? '—'} · {pass.result_status} · {pass.failed_attempt_count} failed · {pass.elapsed_seconds.value == null ? '—' : `${pass.elapsed_seconds.value.toFixed(2)} s`}</p>{pass.attempts.map(a => <p key={a.attempt_id}>{a.attempt_id} · {a.acceptance_status} · {a.generation_status} · {a.reported_model ?? '—'} · {a.elapsed_seconds == null ? '—' : `${a.elapsed_seconds.toFixed(2)} s`}</p>)}</details>))}</div></Panel>}
      {phase === 'publish' && <Activity id={id} publicationOnly expanded title="Publication log" />}
    </div></div>}
  </main>
}
